### ISSUE TITLE
caffe2csv kernel_size issue

### ISSUE THREAD

**Issue by avspavan** [hahnyuan/nn_tools#10]
Hi,

I think there is a bug in the caffe 2 csv converter. The self.kernel_size is of size 1 instead of 2, for example. So i had to put a hack to make it work here (self.kernel_size[0], self.kernel_size[0]): https://github.com/hahnyuan/nn_tools/blob/master/analysis/CaffeA.py#L20. 

Thanks,
Pavan

**Comment by hahnyuan** [comment]
Hi,
Thanks for your remind.
The type of kernel_size is <class google.protobuf.pyext._message.RepeatedScalarContainer'>, When one of the prototxt's kernel_size is omitted, there should be a AssertionError. 
I have changed the assertion logic to solve this problem.

Zhihang
