### ISSUE TITLE
torch.view seems don't supporting?

### ISSUE THREAD

**Issue by bigbrother33** [hahnyuan/nn_tools#18]

**Comment by OPPOA113** [comment]
@bigbrother33 had you solver the problem.
![image](https://user-images.githubusercontent.com/4974108/67846403-27737b80-fb3c-11e9-9b3f-1a0cd6f04175.png)
what should i do

**Comment by riskeverything** [comment]
嗨，你找到解决办法了嘛？我看了源码中view函数，那个dims=0，没看懂，貌似在pytorch中view就会出错。
