### ISSUE TITLE
caffe_analyser.py 无输出

### ISSUE THREAD

**Issue by duchengyao** [hahnyuan/nn_tools#2]
你好，我使用`python caffe_analyser.py resnet_18_deploy.prototxt analys_result.csv 1,224,224,3`测试了一下您的程序，发现输出的csv文件为空

是不是因为[CaffeA.py](https://github.com/hahnyuan/nn_tools/blob/master/analysis/CaffeA.py#L16)的以下代码给清空了呀
```
            # first remove the node from not_ref
            try:not_ref.remove(blob_dict[layer.bottom[0]])
            except:pass
```

谢谢^_^

**Comment by PKUZHOU** [comment]
现在这个问题已经解决了，作者把remove the node from not_ref移到了后面，如果识别不了这个层会把not_ref 的blob删掉的情况。
第二个解决的问题是加入了softmax 的支持
