### ISSUE TITLE
errors encountered when convert the resnet50 model

### ISSUE THREAD

**Issue by catsglasses** [hahnyuan/nn_tools#5]
When I try to convert the resnet50 model, errors encountered, the convertion code and erros pasted in the following:

convertion code: 
    name = 'resnet50'
    net = resnet50(True)
    net.eval()
    input=Variable(torch.ones([1,3,256,128]))
    pytorch_to_caffe.trans_net(net,input,name)
    pytorch_to_caffe.save_prototxt('{}.prototxt'.format(name))
    pytorch_to_caffe.save_caffemodel('{}.caffemodel'.format(name))

errors:
WARNING: the output shape miss match at max_pool4: input torch.Size([1, 64, 128, 64]) output---Pytorch:torch.Size([1, 64, 64, 32])---Caffe:torch.Size([1, 64, 65, 33])
This is caused by the different implementation that ceil mode in caffe and the floor mode in pytorch.
You can add the clip layer in caffe prototxt manually if shape mismatch error is caused in caffe. 
Traceback (most recent call last):
nn_tools\example\inceptionv3_pytorch_to_caffe.py", line 18, in <module>
    pytorch_to_caffe.trans_net(net,input,name)
  File ".\pytorch_to_caffe.py", line 336, in trans_net
    out = net.forward(input_var)
  File "C:\Python36\lib\site-packages\torchvision\models\resnet.py", line 149, in forward
    x = self.avgpool(x)
  File "C:\Python36\lib\site-packages\torch\nn\modules\module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Python36\lib\site-packages\torch\nn\modules\pooling.py", line 506, in forward
    self.padding, self.ceil_mode, self.count_include_pad)
  File ".\pytorch_to_caffe.py", line 300, in __call__
    out=self.obj(self.raw,*args,**kwargs)
  File ".\pytorch_to_caffe.py", line 143, in _avg_pool2d
    x = raw(input, kernel_size, stride, padding, ceil_mode, count_include_pad)
RuntimeError: Given input size: (2048x8x4). Calculated output size: (2048x2x-2). Output size is too small at c:\pytorch\torch\lib\thnn\generic/SpatialAveragePooling.c:64

Can you help me fix the error? Thanks a lot.

**Comment by chegnyanjun** [comment]
Did you solved the problem ,I have met the same problem like you ,Can you give me some suggestion?

**Comment by hahnyuan** [comment]
@catsglasses Your input size is not compatable to resnet50. The input size of this model should be 224x224.
ref: https://pytorch.org/docs/master/torchvision/models.html

**Comment by razpanyvision** [comment]
> Hi guys, I have solved this problem, caffe and pytorch used different round method.

Can you elaborate?
