### ISSUE TITLE
convert fail on some Model

### ISSUE THREAD

**Issue by my1347** [hahnyuan/nn_tools#6]
Dear yuan
Your tool works perfect on my other Nets'
But this one,
Covert fail, duddy. 
![image](https://user-images.githubusercontent.com/5409816/39392917-1e3688b6-4af1-11e8-877f-248e38f6658d.png)
![image](https://user-images.githubusercontent.com/5409816/39392919-2cee3dfe-4af1-11e8-8c5f-f8f93b17e796.png)

![image](https://user-images.githubusercontent.com/5409816/39392927-5b409c6a-4af1-11e8-9967-db893d048299.png)

**Comment by hahnyuan** [comment]
Hi, nn.Conv1d is not supported in Caffe. But we can using a conv2d with 3x1 kernel and the input height = 1 to do the same as the Conv1d.

**Comment by my1347** [comment]
@hahnyuan thank you so much ,buddy
